---
development:
  cloud_name: ongmungazi
  api_key: '732316269896155'
  api_secret: zyBB6-mWQ-bwCNZtzyStdIGF53M
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: ongmungazi
  api_key: '732316269896155'
  api_secret: zyBB6-mWQ-bwCNZtzyStdIGF53M
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: ongmungazi
  api_key: '732316269896155'
  api_secret: zyBB6-mWQ-bwCNZtzyStdIGF53M
  enhance_image_tag: true
  static_file_support: false
